package tatteo.view;


public class Agg_vuelo extends javax.swing.JFrame {

    
    public Agg_vuelo() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Origen_lbl = new javax.swing.JLabel();
        Destino_lbl = new javax.swing.JLabel();
        Dur_lbl = new javax.swing.JLabel();
        NumVuelo_lbl = new javax.swing.JLabel();
        Aero_lbl = new javax.swing.JLabel();
        Costo_lbl = new javax.swing.JLabel();
        ori_field = new javax.swing.JTextField();
        dest_field = new javax.swing.JTextField();
        dur_field = new javax.swing.JTextField();
        numF_field = new javax.swing.JTextField();
        aero_field = new javax.swing.JTextField();
        price_field = new javax.swing.JTextField();
        AddListVue_btn = new javax.swing.JButton();
        ver_lista_btn = new javax.swing.JButton();
        ir_inicio_btn = new javax.swing.JButton();
        AddCiu_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Nuevo Vuelo");

        Origen_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        Origen_lbl.setText("Origen");

        Destino_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        Destino_lbl.setText("Destino");

        Dur_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        Dur_lbl.setText("Duración");

        NumVuelo_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        NumVuelo_lbl.setText("Numero de Vuelo");

        Aero_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        Aero_lbl.setText("Aerolínea");

        Costo_lbl.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        Costo_lbl.setText("Costo del Boleto");

        ori_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ori_fieldActionPerformed(evt);
            }
        });

        AddListVue_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        AddListVue_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/menu.png"))); // NOI18N
        AddListVue_btn.setText("Añadir a Lista");
        AddListVue_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddListVue_btnActionPerformed(evt);
            }
        });

        ver_lista_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        ver_lista_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/list.png"))); // NOI18N
        ver_lista_btn.setText("Ver Lista");
        ver_lista_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_lista_btnActionPerformed(evt);
            }
        });

        ir_inicio_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        ir_inicio_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/home.png"))); // NOI18N
        ir_inicio_btn.setText("Inicio");
        ir_inicio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ir_inicio_btnActionPerformed(evt);
            }
        });

        AddCiu_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        AddCiu_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/add.png"))); // NOI18N
        AddCiu_btn.setText("Add Ciudad");
        AddCiu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCiu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Destino_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dest_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Origen_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ori_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dur_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dur_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumVuelo_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numF_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Aero_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aero_field))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Costo_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddCiu_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddListVue_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ver_lista_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ir_inicio_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Origen_lbl)
                    .addComponent(ori_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCiu_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Destino_lbl)
                    .addComponent(dest_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dur_lbl)
                    .addComponent(dur_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumVuelo_lbl)
                    .addComponent(numF_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aero_lbl)
                    .addComponent(aero_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Costo_lbl)
                    .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddListVue_btn)
                    .addComponent(ver_lista_btn)
                    .addComponent(ir_inicio_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ori_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ori_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ori_fieldActionPerformed

    private void ir_inicio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ir_inicio_btnActionPerformed
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ir_inicio_btnActionPerformed

    private void ver_lista_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_lista_btnActionPerformed
        
        Lista_vuelos vuelos = new Lista_vuelos();
        vuelos.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_ver_lista_btnActionPerformed

    private void AddListVue_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddListVue_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddListVue_btnActionPerformed

    private void AddCiu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCiu_btnActionPerformed
        
        Lista_ciudades ciudades = new Lista_ciudades();
        ciudades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddCiu_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agg_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agg_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agg_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agg_vuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agg_vuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCiu_btn;
    private javax.swing.JButton AddListVue_btn;
    private javax.swing.JLabel Aero_lbl;
    private javax.swing.JLabel Costo_lbl;
    private javax.swing.JLabel Destino_lbl;
    private javax.swing.JLabel Dur_lbl;
    private javax.swing.JLabel NumVuelo_lbl;
    private javax.swing.JLabel Origen_lbl;
    private javax.swing.JTextField aero_field;
    private javax.swing.JTextField dest_field;
    private javax.swing.JTextField dur_field;
    private javax.swing.JButton ir_inicio_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numF_field;
    private javax.swing.JTextField ori_field;
    private javax.swing.JTextField price_field;
    private javax.swing.JButton ver_lista_btn;
    // End of variables declaration//GEN-END:variables

    
}
