/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tatteo.view;

/**
 *
 * @author itaca
 */
public class Lista_de_vuelos extends javax.swing.JFrame {

    /**
     * Creates new form Vuelos
     */
    public Lista_de_vuelos() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_vuelos_tabla = new javax.swing.JTable();
        add_vuelo_bt = new javax.swing.JButton();
        del_vuelo_bt = new javax.swing.JButton();
        mod_vuelo_bt = new javax.swing.JButton();
        inicio_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Swis721 Ex BT", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Vuelos");

        lista_vuelos_tabla.setFont(new java.awt.Font("Swis721 Lt BT", 0, 18)); // NOI18N
        lista_vuelos_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Numero de Vuelo", "Aerolínea"
            }
        ));
        jScrollPane1.setViewportView(lista_vuelos_tabla);

        add_vuelo_bt.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        add_vuelo_bt.setText("Agregar Vuelo");
        add_vuelo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_vuelo_btActionPerformed(evt);
            }
        });

        del_vuelo_bt.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        del_vuelo_bt.setText("Eliminar Vuelo");
        del_vuelo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_vuelo_btActionPerformed(evt);
            }
        });

        mod_vuelo_bt.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        mod_vuelo_bt.setText("Modificar Vuelo");
        mod_vuelo_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_vuelo_btActionPerformed(evt);
            }
        });

        inicio_bt.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        inicio_bt.setText("Inicio");
        inicio_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(add_vuelo_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(del_vuelo_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mod_vuelo_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inicio_bt)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_vuelo_bt)
                    .addComponent(del_vuelo_bt)
                    .addComponent(mod_vuelo_bt)
                    .addComponent(inicio_bt))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void del_vuelo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_vuelo_btActionPerformed
        // TODO add your handling code here:
        del_vuelo ventanaDel = new del_vuelo();
        ventanaDel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_del_vuelo_btActionPerformed

    private void mod_vuelo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_vuelo_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mod_vuelo_btActionPerformed

    private void inicio_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_btActionPerformed
        // TODO add your handling code here:
//        Inicio ventanaInicio = new Inicio();
//        ventanaInicio.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_inicio_btActionPerformed

    private void add_vuelo_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_vuelo_btActionPerformed
        // TODO add your handling code here:
        agg_vuelo ventanaAdd = new agg_vuelo();
        ventanaAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_vuelo_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_de_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_de_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_de_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_de_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_de_vuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_vuelo_bt;
    private javax.swing.JButton del_vuelo_bt;
    private javax.swing.JButton inicio_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lista_vuelos_tabla;
    private javax.swing.JButton mod_vuelo_bt;
    // End of variables declaration//GEN-END:variables
}
