
package tatteo.view;


public class Lista_vuelos extends javax.swing.JFrame {

    
    public Lista_vuelos() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        list_vuelos_tab = new javax.swing.JScrollPane();
        lista_vuelos_tabla = new javax.swing.JTable();
        add_vuelo_btn = new javax.swing.JButton();
        del_vuelo_btn = new javax.swing.JButton();
        modif_vuelo_btn = new javax.swing.JButton();
        plan_vuelo_btn = new javax.swing.JButton();
        ir_inicio_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Swis721 Ex BT", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Vuelos");

        lista_vuelos_tabla.setFont(new java.awt.Font("Swis721 Lt BT", 0, 18)); // NOI18N
        lista_vuelos_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Numero de Vuelo", "Aerolínea"
            }
        ));
        list_vuelos_tab.setViewportView(lista_vuelos_tabla);

        add_vuelo_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        add_vuelo_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/add.png"))); // NOI18N
        add_vuelo_btn.setText("Add Vuelo");
        add_vuelo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_vuelo_btnActionPerformed(evt);
            }
        });

        del_vuelo_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        del_vuelo_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/delete.png"))); // NOI18N
        del_vuelo_btn.setText("Del Vuelo");
        del_vuelo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_vuelo_btnActionPerformed(evt);
            }
        });

        modif_vuelo_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        modif_vuelo_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/conf.png"))); // NOI18N
        modif_vuelo_btn.setText("Modif Vuelo");
        modif_vuelo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modif_vuelo_btnActionPerformed(evt);
            }
        });

        plan_vuelo_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        plan_vuelo_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/track.png"))); // NOI18N
        plan_vuelo_btn.setText("Generar Plan ");
        plan_vuelo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plan_vuelo_btnActionPerformed(evt);
            }
        });

        ir_inicio_btn.setFont(new java.awt.Font("Swis721 Lt BT", 1, 14)); // NOI18N
        ir_inicio_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/home.png"))); // NOI18N
        ir_inicio_btn.setText("Inicio");
        ir_inicio_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ir_inicio_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list_vuelos_tab, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(add_vuelo_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(del_vuelo_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modif_vuelo_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ir_inicio_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plan_vuelo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(list_vuelos_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_vuelo_btn)
                    .addComponent(del_vuelo_btn)
                    .addComponent(modif_vuelo_btn)
                    .addComponent(plan_vuelo_btn))
                .addGap(18, 18, 18)
                .addComponent(ir_inicio_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void del_vuelo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_vuelo_btnActionPerformed
        
        Modif_vuelo ventanaDel = new Modif_vuelo();
        ventanaDel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_del_vuelo_btnActionPerformed

    private void modif_vuelo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modif_vuelo_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modif_vuelo_btnActionPerformed

    private void plan_vuelo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plan_vuelo_btnActionPerformed
        
        Generar_plan genPlan = new Generar_plan();
        genPlan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_plan_vuelo_btnActionPerformed

    private void add_vuelo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_vuelo_btnActionPerformed
        
        Agg_vuelo aggVuelo = new Agg_vuelo();
        aggVuelo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_vuelo_btnActionPerformed

    private void ir_inicio_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ir_inicio_btnActionPerformed
        
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ir_inicio_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_vuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_vuelo_btn;
    private javax.swing.JButton del_vuelo_btn;
    private javax.swing.JButton ir_inicio_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane list_vuelos_tab;
    private javax.swing.JTable lista_vuelos_tabla;
    private javax.swing.JButton modif_vuelo_btn;
    private javax.swing.JButton plan_vuelo_btn;
    // End of variables declaration//GEN-END:variables
}
