
import tatteo.view.Lista_de_vuelos;
import tatteo.view.agg_vuelo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author itaca
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuInicio = new javax.swing.JMenuBar();
        Vuelos = new javax.swing.JMenu();
        ListFlights = new javax.swing.JMenuItem();
        AddFlight = new javax.swing.JMenuItem();
        DeleteFlight = new javax.swing.JMenuItem();
        ModFlight = new javax.swing.JMenuItem();
        FlightPlan = new javax.swing.JMenuItem();
        Repositorio = new javax.swing.JMenu();
        LoadFile = new javax.swing.JMenuItem();
        ActRepositorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/avion.png"))); // NOI18N
        Vuelos.setText("VUELOS");

        ListFlights.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/list.png"))); // NOI18N
        ListFlights.setText("Lista de Vuelos");
        ListFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListFlightsActionPerformed(evt);
            }
        });
        Vuelos.add(ListFlights);

        AddFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/add.png"))); // NOI18N
        AddFlight.setText("Agregar vuelo");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });
        Vuelos.add(AddFlight);

        DeleteFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/delete.png"))); // NOI18N
        DeleteFlight.setText("Eliminar vuelo");
        DeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFlightActionPerformed(evt);
            }
        });
        Vuelos.add(DeleteFlight);

        ModFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/conf2.png"))); // NOI18N
        ModFlight.setText("Modificar vuelo");
        Vuelos.add(ModFlight);

        FlightPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/track.png"))); // NOI18N
        FlightPlan.setText("Generar plan de vuelo");
        Vuelos.add(FlightPlan);

        MenuInicio.add(Vuelos);

        Repositorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/menu.png"))); // NOI18N
        Repositorio.setText("REPOSITORIO");

        LoadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/outbox.png"))); // NOI18N
        LoadFile.setText("Cargar archivo");
        Repositorio.add(LoadFile);

        ActRepositorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tatteo/img/reload.png"))); // NOI18N
        ActRepositorio.setText("Actualizar repositorio");
        Repositorio.add(ActRepositorio);

        MenuInicio.add(Repositorio);

        setJMenuBar(MenuInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListFlightsActionPerformed
        // TODO add your handling code here:
        Lista_de_vuelos ventanaList = new Lista_de_vuelos();
        ventanaList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListFlightsActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        // TODO add your handling code here:
        agg_vuelo ventanaAdd = new agg_vuelo();
        ventanaAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void DeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActRepositorio;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenuItem DeleteFlight;
    private javax.swing.JMenuItem FlightPlan;
    private javax.swing.JMenuItem ListFlights;
    private javax.swing.JMenuItem LoadFile;
    private javax.swing.JMenuBar MenuInicio;
    private javax.swing.JMenuItem ModFlight;
    private javax.swing.JMenu Repositorio;
    private javax.swing.JMenu Vuelos;
    // End of variables declaration//GEN-END:variables
}
